# Changes here will be overwritten by Copier
_commit: 4.0.1
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: 1576793+Mark-Booth@users.noreply.github.com
author_name: Mark Booth
component_lifecycle: experimental
component_owner: group:default/data-acquisition
component_type: library
description: Bluesky plans, plan stubs, and utilities for crystallography beamlines
distribution_name: crystallography-bluesky
docker: false
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: crystallography_bluesky
pypi: false
repo_name: crystallography-bluesky
strict_typing: true
type_checker: pyright
